top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/echo
builddir     = /root/httpd-2.4.41/modules/echo
VPATH        = /root/httpd-2.4.41/modules/echo

include $(top_srcdir)/build/special.mk

