top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/core
builddir     = /root/httpd-2.4.41/modules/core
VPATH        = /root/httpd-2.4.41/modules/core

include $(top_srcdir)/build/special.mk

