top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/server/mpm/worker
builddir     = /root/httpd-2.4.41/server/mpm/worker
VPATH        = /root/httpd-2.4.41/server/mpm/worker

include $(top_srcdir)/build/special.mk
