top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules
builddir     = /root/httpd-2.4.41/modules
VPATH        = /root/httpd-2.4.41/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

