top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/os
builddir     = /root/httpd-2.4.41/os
VPATH        = /root/httpd-2.4.41/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
