top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/loggers
builddir     = /root/httpd-2.4.41/modules/loggers
VPATH        = /root/httpd-2.4.41/modules/loggers

include $(top_srcdir)/build/special.mk

