top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/aaa
builddir     = /root/httpd-2.4.41/modules/aaa
VPATH        = /root/httpd-2.4.41/modules/aaa

include $(top_srcdir)/build/special.mk

