top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/http
builddir     = /root/httpd-2.4.41/modules/http
VPATH        = /root/httpd-2.4.41/modules/http

include $(top_srcdir)/build/special.mk

