top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/arch/win32
builddir     = /root/httpd-2.4.41/modules/arch/win32
VPATH        = /root/httpd-2.4.41/modules/arch/win32
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
