top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/server/mpm/prefork
builddir     = /root/httpd-2.4.41/server/mpm/prefork
VPATH        = /root/httpd-2.4.41/server/mpm/prefork
include $(top_srcdir)/build/special.mk
