top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/generators
builddir     = /root/httpd-2.4.41/modules/generators
VPATH        = /root/httpd-2.4.41/modules/generators

include $(top_srcdir)/build/special.mk

