top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/metadata
builddir     = /root/httpd-2.4.41/modules/metadata
VPATH        = /root/httpd-2.4.41/modules/metadata

include $(top_srcdir)/build/special.mk

