top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/filters
builddir     = /root/httpd-2.4.41/modules/filters
VPATH        = /root/httpd-2.4.41/modules/filters

include $(top_srcdir)/build/special.mk

