top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/cache
builddir     = /root/httpd-2.4.41/modules/cache
VPATH        = /root/httpd-2.4.41/modules/cache

include $(top_srcdir)/build/special.mk

