top_srcdir   = /root/httpd-2.4.41
top_builddir = /root/httpd-2.4.41
srcdir       = /root/httpd-2.4.41/modules/mappers
builddir     = /root/httpd-2.4.41/modules/mappers
VPATH        = /root/httpd-2.4.41/modules/mappers

include $(top_srcdir)/build/special.mk

